server:
  port: 8901


management:
  endpoints:
    web:
      exposure:
        include: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream


