spring:
  application:
    name: auth-service
  # zipkin 配置
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0  # 配置采样比例为100%，默认值为0.1 实践中根据需要调整


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


server:
  port: 8763



